export const API_BASE_URL = "https://api.skyscope.app/api/v1";

export const FLIGHTS_REFETCH_INTERVAL_IN_SECONDS = 30;
export const FLIGHTS_REFETCH_INTERVAL_IN_MILLISECONDS =
  FLIGHTS_REFETCH_INTERVAL_IN_SECONDS * 1000;

export const ATCS_REFETCH_INTERVAL_IN_SECONDS = 60;
export const ATCS_REFETCH_INTERVAL_IN_MILLISECONDS =
  ATCS_REFETCH_INTERVAL_IN_SECONDS * 1000;

export const WEATHER_REFETCH_INTERVAL_IN_SECONDS = 60 * 30;
export const WEATHER_REFETCH_INTERVAL_IN_MILLISECONDS =
  WEATHER_REFETCH_INTERVAL_IN_SECONDS * 1000;
