import { cn } from '@/lib/utils';

import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';
import { Tektur as FontLogo } from 'next/font/google';

import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { ClientProviders } from './client-providers';

import '@/styles/colors.css';
import '@/styles/globals.css';

const fontLogo = FontLogo({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-logo',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen h-full flex", GeistSans.variable, GeistMono.variable, fontLogo.variable)}>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  )
}
