import { cn } from '@/lib/utils';
import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { ClientProviders } from './client-providers';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background antialiased flex", GeistSans.variable, GeistMono.variable)}>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  )
}
